//! MultiObjectiveOptimizer implementations for the engine.
//!
//! Both adapters here delegate to a real algorithm in [`crate::multi_objective`]:
//! [`NSGA2Optimizer`] to `NSGA2`, [`WeightedSumOptimizer`] to `WeightedSum`.
//!
//! The `NSGA3Optimizer` / `MOEADOptimizer` / `PAESOptimizer` / `SPEA2Optimizer`
//! placeholders that used to live here were generated by a macro whose
//! `update_pareto_front` returned an empty Pareto front and whose
//! `calculate_diversity` returned a hardcoded `0.5`. They were reachable —
//! `create_multi_objective_optimizer` instantiated them for the corresponding
//! `MultiObjectiveAlgorithm` values — so a search configured for NSGA-III or
//! SPEA2 silently produced no front at all while reporting a fabricated
//! diversity. They are gone; those algorithms now yield an honest
//! `OptimError::NotImplemented` at engine construction.

use crate::error::Result;
use crate::multi_objective;
use crate::nas_engine::config::*;
use crate::nas_engine::resources::*;
use crate::nas_engine::results::*;
use scirs2_core::numeric::Float;
use scirs2_core::RngExt;
use std::fmt::Debug;

use super::support::MultiObjectiveOptimizer;

/// NSGA-II multi-objective optimizer wrapper that delegates Pareto-front
/// maintenance, candidate selection and diversity measurement to the complete
/// [`crate::multi_objective::NSGA2`] implementation.
pub(super) struct NSGA2Optimizer<
    T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum,
> {
    /// Live NSGA-II engine holding population, Pareto front and statistics.
    pub(super) inner: crate::multi_objective::NSGA2<T>,
    /// Configured objectives (direction + metric mapping) required by NSGA-II
    /// to compute dominance.
    pub(super) config: MultiObjectiveConfig<T>,
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum>
    NSGA2Optimizer<T>
{
    /// Construct an NSGA-II optimizer from a multi-objective configuration. The
    /// inner [`crate::multi_objective::NSGA2`] is created with standard
    /// crossover/mutation probabilities; its population is (re)sized per update
    /// so that every individual carries real objective values.
    pub fn new(config: &MultiObjectiveConfig<T>) -> Result<Self> {
        use crate::multi_objective::MultiObjectiveOptimizer as InnerMultiObjective;
        let mut inner = crate::multi_objective::NSGA2::<T>::new(1, 0.9, 0.1);
        inner.initialize(config)?;
        Ok(Self {
            inner,
            config: config.clone(),
        })
    }
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum>
    MultiObjectiveOptimizer<T> for NSGA2Optimizer<T>
{
    fn update_pareto_front(
        &mut self,
        results: &[SearchResult<T>],
    ) -> Result<multi_objective::ParetoFront<T>> {
        use crate::multi_objective::MultiObjectiveOptimizer as InnerMultiObjective;
        if results.is_empty() {
            return Ok(self.inner.get_pareto_front().clone());
        }
        // The *same* NSGA-II instance is reused across generations on purpose: it
        // latches the hypervolume reference point on first use and remembers the
        // previous hypervolume to derive the `convergence` metric. Rebuilding it
        // per call (as this adapter used to) re-derived the reference from every
        // new front, which made hypervolumes from different generations
        // incomparable and pinned `convergence` at 1 forever.
        Ok(self.inner.pareto_front_from_results(results))
    }
    fn select_candidates(
        &self,
        candidates: &[SearchResult<T>],
        population_size: usize,
    ) -> Result<Vec<SearchResult<T>>> {
        use crate::multi_objective::MultiObjectiveOptimizer as InnerMultiObjective;
        if candidates.is_empty() || population_size == 0 {
            return Ok(Vec::new());
        }
        let mut ranker = crate::multi_objective::NSGA2::<T>::new(candidates.len(), 0.9, 0.1);
        ranker.initialize(&self.config)?;
        let selected_indices = ranker.select_by_rank_and_crowding(candidates, population_size);
        Ok(selected_indices
            .into_iter()
            .map(|idx| candidates[idx].clone())
            .collect())
    }
    fn calculate_diversity(&self, population: &[SearchResult<T>]) -> f64 {
        self.inner.mean_objective_distance(population)
    }
}
/// Weighted-sum multi-objective optimizer wrapper delegating to the real
/// [`crate::multi_objective::WeightedSum`] scalarizer.
///
/// This adapter previously did not exist: `MultiObjectiveAlgorithm::WeightedSum`
/// was silently served by NSGA-II, so the configured per-objective `weight`
/// values were ignored entirely.
pub(super) struct WeightedSumOptimizer<
    T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum,
> {
    pub(super) inner: crate::multi_objective::WeightedSum<T>,
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum>
    WeightedSumOptimizer<T>
{
    pub fn new(config: &MultiObjectiveConfig<T>) -> Result<Self> {
        Ok(Self {
            inner: crate::multi_objective::WeightedSum::new(&config.objectives)?,
        })
    }
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + PartialOrd + std::iter::Sum>
    MultiObjectiveOptimizer<T> for WeightedSumOptimizer<T>
{
    fn update_pareto_front(
        &mut self,
        results: &[SearchResult<T>],
    ) -> Result<multi_objective::ParetoFront<T>> {
        use crate::multi_objective::MultiObjectiveOptimizer as InnerMultiObjective;
        self.inner.update_pareto_front(results)
    }

    fn select_candidates(
        &self,
        candidates: &[SearchResult<T>],
        population_size: usize,
    ) -> Result<Vec<SearchResult<T>>> {
        if candidates.is_empty() || population_size == 0 {
            return Ok(Vec::new());
        }
        // Rank by the configured weighted-sum scalarization (direction aware),
        // then keep the best `population_size`.
        let mut scored: Vec<(usize, T)> = candidates
            .iter()
            .enumerate()
            .map(|(idx, result)| (idx, self.inner.scalarized_cost_for_result(result)))
            .collect();
        scored.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
        Ok(scored
            .into_iter()
            .take(population_size)
            .map(|(idx, _)| candidates[idx].clone())
            .collect())
    }

    fn calculate_diversity(&self, population: &[SearchResult<T>]) -> f64 {
        self.inner.mean_objective_distance(population)
    }
}
