//! SearchStrategy implementations: real RandomStrategy/EvolutionaryStrategy adapters over crate::search_strategies, plus the never-instantiated placeholder strategies generated by impl_search_strategy!.

use crate::error::Result;
use crate::nas_engine::config::*;
use crate::nas_engine::resources::*;
use crate::nas_engine::results::*;
use scirs2_core::numeric::Float;
use scirs2_core::RngExt;
use std::collections::{HashMap, VecDeque};
use std::fmt::Debug;

use super::support::SearchStrategy;

pub(super) struct BayesianStrategy<T: Float + Debug + Send + Sync + 'static> {
    pub(super) _phantom: std::marker::PhantomData<T>,
}
pub(super) struct DifferentiableStrategy<T: Float + Debug + Send + Sync + 'static> {
    pub(super) _phantom: std::marker::PhantomData<T>,
}
/// Evolutionary search strategy wrapper.
///
/// Holds a live [`crate::search_strategies::EvolutionarySearch`] which performs
/// tournament selection, crossover and mutation from the search history (and
/// falls back to random sampling when history is insufficient). Tracks the
/// best score per generation to drive a real convergence criterion.
pub(super) struct EvolutionaryStrategy<
    T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum,
> {
    pub(super) inner: crate::search_strategies::EvolutionarySearch<T>,
    pub(super) search_space: SearchSpaceConfig,
    pub(super) batch_size: usize,
    /// Best overall score observed in each `update_strategy` call, used to
    /// detect a lack of improvement over the most recent generations.
    pub(super) best_score_history: Vec<T>,
    /// Number of trailing generations without improvement that signals
    /// convergence.
    pub(super) convergence_patience: usize,
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum>
    EvolutionaryStrategy<T>
{
    /// Construct an evolutionary strategy from a NAS configuration, wrapping a
    /// live [`crate::search_strategies::EvolutionarySearch`] sized to the
    /// configured population.
    pub fn new(config: &NASConfig<T>) -> Result<Self> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        let population_size = config.population_size.max(2);
        let convergence_patience = config.early_stopping.patience.max(5);
        let mut inner =
            crate::search_strategies::EvolutionarySearch::<T>::new(population_size, 0.1, 0.8, 3);
        inner.initialize(&config.search_space)?;
        let batch_size = if config.population_size > 0 {
            config.population_size
        } else {
            8
        };
        Ok(Self {
            inner,
            search_space: config.search_space.clone(),
            batch_size,
            best_score_history: Vec::new(),
            convergence_patience,
        })
    }
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum> SearchStrategy<T>
    for EvolutionaryStrategy<T>
{
    fn generate_candidates(
        &mut self,
        history: &VecDeque<SearchResult<T>>,
    ) -> Result<Vec<OptimizerArchitecture<T>>> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        let mut candidates = Vec::with_capacity(self.batch_size);
        for _ in 0..self.batch_size {
            let architecture = self
                .inner
                .generate_architecture(&self.search_space, history)?;
            candidates.push(architecture);
        }
        Ok(candidates)
    }
    fn update_strategy(&mut self, results: &[SearchResult<T>]) -> Result<()> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        if !results.is_empty() {
            let best = results
                .iter()
                .map(|r| r.evaluation_results.overall_score)
                .fold(
                    T::neg_infinity(),
                    |acc, score| {
                        if score > acc {
                            score
                        } else {
                            acc
                        }
                    },
                );
            if best > T::neg_infinity() {
                self.best_score_history.push(best);
            }
        }
        self.inner.update_with_results(results)
    }
    fn has_converged(&self) -> bool {
        let window = self.convergence_patience;
        if self.best_score_history.len() <= window {
            return false;
        }
        let len = self.best_score_history.len();
        let recent_best = self.best_score_history[len - window..]
            .iter()
            .fold(T::neg_infinity(), |acc, &s| if s > acc { s } else { acc });
        let prior_best = self.best_score_history[..len - window]
            .iter()
            .fold(T::neg_infinity(), |acc, &s| if s > acc { s } else { acc });
        recent_best <= prior_best
    }
    fn strategy_name(&self) -> &str {
        "EvolutionaryStrategy"
    }
}
pub(super) struct HybridStrategy<T: Float + Debug + Send + Sync + 'static> {
    pub(super) _phantom: std::marker::PhantomData<T>,
}
pub(super) struct ProgressiveStrategy<T: Float + Debug + Send + Sync + 'static> {
    pub(super) _phantom: std::marker::PhantomData<T>,
}
/// Random search strategy wrapper.
///
/// Holds a live [`crate::search_strategies::RandomSearch`] together with the
/// search space and batch size so that `generate_candidates` produces a real
/// batch of randomly-sampled valid architectures.
pub(super) struct RandomStrategy<
    T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum,
> {
    pub(super) inner: crate::search_strategies::RandomSearch<T>,
    pub(super) search_space: SearchSpaceConfig,
    pub(super) batch_size: usize,
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum>
    RandomStrategy<T>
{
    /// Construct a random-search strategy from a NAS configuration. A live
    /// [`crate::search_strategies::RandomSearch`] is seeded deterministically
    /// and initialized with the configured search space.
    pub fn new(config: &NASConfig<T>) -> Result<Self> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        let mut inner = crate::search_strategies::RandomSearch::<T>::new(Some(42));
        inner.initialize(&config.search_space)?;
        let batch_size = if config.population_size > 0 {
            config.population_size
        } else {
            8
        };
        Ok(Self {
            inner,
            search_space: config.search_space.clone(),
            batch_size,
        })
    }
    /// Synthesize a single valid architecture without indexing into the
    /// (possibly empty) component config list. Used when the search space
    /// provides no per-component hyperparameter configs but still declares the
    /// component vocabulary via `component_types`.
    pub(super) fn synthesize_from_component_types(&self, index: usize) -> OptimizerArchitecture<T> {
        let component_label = self
            .search_space
            .component_types
            .first()
            .map(|ct| format!("{:?}", ct))
            .unwrap_or_else(|| "Adam".to_string());
        OptimizerArchitecture {
            components: vec![component_label],
            parameters: HashMap::new(),
            connections: Vec::new(),
            metadata: HashMap::new(),
            hyperparameters: HashMap::new(),
            architecture_id: format!("random_arch_{}", index),
        }
    }
}
impl<T: Float + Debug + Default + Clone + Send + Sync + 'static + std::iter::Sum> SearchStrategy<T>
    for RandomStrategy<T>
{
    fn generate_candidates(
        &mut self,
        history: &VecDeque<SearchResult<T>>,
    ) -> Result<Vec<OptimizerArchitecture<T>>> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        let mut candidates = Vec::with_capacity(self.batch_size);
        for idx in 0..self.batch_size {
            if self.search_space.components.is_empty() {
                candidates.push(self.synthesize_from_component_types(idx));
            } else {
                let architecture = self
                    .inner
                    .generate_architecture(&self.search_space, history)?;
                candidates.push(architecture);
            }
        }
        Ok(candidates)
    }
    fn update_strategy(&mut self, results: &[SearchResult<T>]) -> Result<()> {
        use crate::search_strategies::SearchStrategy as InnerSearchStrategy;
        self.inner.update_with_results(results)
    }
    fn has_converged(&self) -> bool {
        false
    }
    fn strategy_name(&self) -> &str {
        "RandomStrategy"
    }
}
pub(super) struct ReinforcementStrategy<T: Float + Debug + Send + Sync + 'static> {
    pub(super) _phantom: std::marker::PhantomData<T>,
}
macro_rules! impl_search_strategy {
    ($strategy:ident) => {
        impl<T: Float + Debug + Send + Sync + 'static> $strategy<T> {
            pub fn new(_config: &NASConfig<T>) -> Result<Self> {
                Ok(Self {
                    _phantom: std::marker::PhantomData,
                })
            }
        }

        impl<T: Float + Debug + Send + Sync + 'static> SearchStrategy<T> for $strategy<T> {
            fn generate_candidates(
                &mut self,
                _history: &VecDeque<SearchResult<T>>,
            ) -> Result<Vec<OptimizerArchitecture<T>>> {
                Ok(Vec::new())
            }

            fn update_strategy(&mut self, _results: &[SearchResult<T>]) -> Result<()> {
                Ok(())
            }

            fn has_converged(&self) -> bool {
                false
            }

            fn strategy_name(&self) -> &str {
                stringify!($strategy)
            }
        }
    };
}

// NOTE: RandomStrategy and EvolutionaryStrategy have real, hand-written
// implementations above. Only the never-instantiated strategies use the
// trivial macro.
impl_search_strategy!(BayesianStrategy);
impl_search_strategy!(ReinforcementStrategy);
impl_search_strategy!(DifferentiableStrategy);
impl_search_strategy!(ProgressiveStrategy);
impl_search_strategy!(HybridStrategy);
